Repository woocommerce/woocommerce-paypal-payments, pull requests merged in 2025-09, with the labels that each got.

#3652 Reorganize ACDC and Fastlane gateway settings modals (5230)
  modules/ppcp-axo-block/resources/js/components/Payment/Payment.js
  modules/ppcp-axo-block/src/AxoBlockPaymentMethod.php
  modules/ppcp-axo/src/Gateway/AxoGateway.php
  modules/ppcp-blocks/resources/js/Components/card-fields.js
  modules/ppcp-blocks/services.php
  modules/ppcp-blocks/src/AdvancedCardPaymentMethod.php
  modules/ppcp-card-fields/src/CardFieldsModule.php
  modules/ppcp-compat/src/Settings/PaymentMethodSettingsMapHelper.php
  modules/ppcp-settings/resources/js/Components/Screens/Settings/Components/Payment/Modal.js
  modules/ppcp-settings/resources/js/Components/Screens/Settings/Tabs/TabPaymentMethods.js
  modules/ppcp-settings/resources/js/data/payment/hooks.js
  modules/ppcp-settings/resources/js/data/payment/reducer.js
  modules/ppcp-settings/src/Data/Definition/PaymentMethodsDefinition.php
  modules/ppcp-settings/src/Data/PaymentSettings.php
  modules/ppcp-settings/src/Endpoint/PaymentRestEndpoint.php
  modules/ppcp-wc-gateway/src/Helper/CardPaymentsConfiguration.php
Labels: bug, enhancement

#3710 Make migration available again (5361)
  modules/ppcp-settings/src/SettingsModule.php
  modules/ppcp-wc-gateway/services.php
Labels: enhancement

#3712 Override flag to keep BCDC for ACDC merchants during migration [5362]
  modules/ppcp-settings/services.php
  modules/ppcp-settings/src/Service/Migration/PaymentSettingsMigration.php
  modules/ppcp-settings/src/SettingsModule.php
  modules/ppcp-wc-gateway/src/Helper/DCCProductStatus.php
Labels: enhancement

#3713 In branded only mode every merchant has bcdc (5366)
  modules/ppcp-settings/src/SettingsModule.php
Labels: enhancement

#3688 Restore PayPal as chosen gateway after App Switch resume (5233)
  modules/ppcp-button/src/ButtonModule.php
Labels: bug
